feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        errorDecoder: com.und.feign.AuthFeignErrorDecoder

spring:
  jpa:
    show-sql: true