## config context path to "/" by setting an empty string
#server:
#  port: 9201
#
## JACKSON
#spring:
#  application:
#    name: client-panel
#  thymeleaf:
#    cache: false
#  jackson:
#    serialization:
#      INDENT_OUTPUT: true
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: ${KAFKA_IP}
#          defaultBrokerPort: ${KAFKA_PORT}
#          zkNodes: ${KAFKA_IP}
#          defaultZkPort: 2181
#          auto-create-topics: true
#          min-partition-count: 1
#          replication-factor: 1
#          configuration:
#            enable:
#              auto:
#                commit: true
#            auto:
#              offset:
#                reset: earliest
#        bindings:
#          scheduleJobSend:
#            producer:
#              configuration:
#                client:
#                  id: 1
#            group: scheduleJobGroup
#            destination: scheduleJobStaging
#          scheduleJobAckReceive:
#            consumer:
#              configuration:
#                enable:
#                  auto:
#                    commit: true
#                auto:
#                  offset:
#                    reset: earliest
#                client:
#                  id: 1
#                group:
#                  id: scheduleJobAckGroup
#            group: scheduleJobAckGroup
#            destination: scheduleJobAckStaging
#          clientEmailSend:
#            producer:
#              configuration:
#                client:
#                  id: 2
#            group: clientEmailSendGroup
#            destination: clientEmailStaging
#          fcmFailureEventReceive:
#            consumer:
#              configuration:
#                enable:
#                  auto:
#                    commit: true
#                auto:
#                  offset:
#                    reset: earliest
#                group:
#                  id: fcmFailureEventGroup
#                client:
#                  id: 2
#            group: fcmFailureEventGroup
#            destination: fcmEventFailureStaging
#          emailFailureEventReceive:
#            consumer:
#              configuration:
#                enable:
#                  auto:
#                    commit: true
#                auto:
#                  offset:
#                    reset: earliest
#                group:
#                  id: emailFailureEventReceiveGroup
#                client:
#                  id: 3
#            group: emailFailureEventReceiveGroup
#            destination: emailFailureEventStaging
#          inEventForLiveSegment:
#            consumer:
#              configuration:
#                group:
#                  id: processLiveEventReceiveGroup
#                client:
#                  id: 4
#            destination: processliveevent
#          outLiveSegment:
#            group: processLiveUserGroup
#            destination: processliveuser
#          inJobForLiveSegmentCheck:
#            consumer:
#              configuration:
#                group:
#                  id: liveUserCheckReceiveGroup
#                client:
#                  id: 5
#            destination: liveusercheck
#          scheduleLiveJobSend:
#            destination: scheduleLiveJobStaging
#          outTestCampaign:
#            destination: testCampaignStaging
#          triggerManualCampaign:
#            destination: manualCampaignStaging
#      bindings:
#        scheduleJobSend:
#          destination: scheduleJobStaging
#        scheduleJobAckReceive:
#          destination: scheduleJobAckStaging
#        clientEmailSend:
#          destination: clientEmailStaging
#        fcmFailureEventReceive:
#          destination: fcmEventFailureStaging
#        emailFailureEventReceive:
#          destination: emailFailureEventStaging
#        inEventForLiveSegment:
#          destination: processliveevent
#        outLiveSegment:
#          destination: processliveuser
#        inJobForLiveSegmentCheck:
#          destination: liveusercheck
#        scheduleLiveJobSend:
#          destination: scheduleLiveJobStaging
#        outTestCampaign:
#          destination: testCampaignStaging
#        triggerManualCampaign:
#          destination: manualCampaignStaging
#
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
#  # Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
#  # Because detection is disabled you have to set correct dialect by hand.
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false
#
#  datasource:
#    url: jdbc:postgresql://${POSTGRES_IP}:${POSTGRES_PORT}/undstaging
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password:  postgres
#    tomcat:
#      initial-size: 10
#      max-wait: 10000
#      max-active: 50
#      test-on-borrow: true
#    hikari:
#      maximum-pool-size: 3
#      idle-timeout: 10000
#  data:
#    mongodb:
#      database: eventdbstaging
#      host: ${MONGO_IP}
#      port: ${MONGO_PORT}
#  flyway:
#    placeholder-replacement: false
#
#  zipkin:
#    base-url: http://127.0.0.1:9411/
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1
#  kafka:
#    bootstrap-servers: ${KAFKA_IP}:${KAFKA_PORT}
#  redis:
#    host: ${REDIS_IP}
#    port: ${REDIS_PORT}
#    database: 1
#  cache:
#    type: redis
#    redis:
#      use-key-prefix: true
#
#security:
#  header:
#    token: Authorization
#    username: UserName
#  secret: mySecret
#  expiration: 604800
#  route:
#    authentication:
#      path: auth
#      refresh: refresh
#
#eureka:
#  instance:
#    prefer-ip-address: true
#    health-check-url-path: /application/health
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    region: desktop
#    service-url:
#      defaultZone: http://${EUREKA_IP}:${EUREKA_PORT_STAGING}/eureka
#
#logging:
#  level:
#    org:
#      springframework: info
#      apache: info
#      hibernate: info
#    com:
#      und: info
#      data:
#        mongodb:
#          core:
#            MongoTemplate: DEBUG
#  file: ${HOME}/log/staging/und-client-panel.log
#
#
#
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: full
#        errorDecoder: com.und.feign.AuthFeignErrorDecoder
#
#
#und:
#  system:
#    user:
#      token: jasdghajskdhg
#    email:
#      setting:
#        id: 1
#  url:
#    event: http://userndot.com/event
#    client: http://userndot.com/client
#    clientui: http://userndot.com/
#  auth-url: http://nestros.com:8080/auth
#  from-email: shiv@userndot.com
#  lambda:
#    funnel:
#      secretKey: tEA3hwNdgerwF4oiVIscjtvEbPIJvwePxrNCAdhv
#      accessKey: AKIAIEEV7Q6MG5DLL52Q
#      region : ap-south-1
#      functionName: FunnelData