spring:
  application:
    name: und-scheduler
  jackson:
    serialization:
      INDENT_OUTPUT: true
      write-dates-as-timestamps: false
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
  jpa:
    hibernate:
      ddl-auto: none
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
using:
  spring:
    schedulerFactory: true


